# Generated by Django 5.2.4 on 2025-08-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('author', models.CharField(default='Admin', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('comments_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
