# Generated by Django 5.2.4 on 2025-08-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog_videos/'),
        ),
    ]
